"""
Unit and Integration Tests for OnePath AI Custom Model & Fallback Architecture
"""

import pytest
from unittest.mock import AsyncMock, patch
from fastapi.testclient import TestClient
from app.main import app
from app.services.custom_model_service import custom_model_service
from app.services.llm_service import llm_service

client = TestClient(app)


def test_custom_model_service_info():
    """Verify service returns operational metadata."""
    info = custom_model_service.get_info()
    assert "enabled" in info
    assert "model_path" in info
    assert "device" in info
    assert "is_loaded" in info


import asyncio

def test_llm_service_primary_custom_model():
    """Test that when custom model answers successfully, Groq is NOT called."""
    async def _run():
        with patch.object(custom_model_service, "is_available", return_value=True), \
             patch.object(custom_model_service, "generate_text", new_callable=AsyncMock) as mock_custom, \
             patch.object(llm_service, "_call_groq", new_callable=AsyncMock) as mock_groq:
            
            mock_custom.return_value = "Answer generated by our custom educational model."
            
            ans = await llm_service.generate_text(prompt="What is force?")
            
            assert ans == "Answer generated by our custom educational model."
            mock_custom.assert_awaited_once()
            mock_groq.assert_not_called()
    asyncio.run(_run())


def test_llm_service_fallback_to_groq_on_custom_failure():
    """Test that when custom model fails or returns empty, it falls back to Groq."""
    async def _run():
        with patch.object(custom_model_service, "is_available", return_value=True), \
             patch.object(custom_model_service, "generate_text", new_callable=AsyncMock) as mock_custom, \
             patch.object(llm_service, "_call_groq", new_callable=AsyncMock) as mock_groq:
            
            # Simulate local model failure / empty response
            mock_custom.return_value = None
            mock_groq.return_value = "Answer generated via Groq fallback."
            
            ans = await llm_service.generate_text(prompt="What is force?")
            
            assert ans == "Answer generated via Groq fallback."
            mock_custom.assert_awaited_once()
            mock_groq.assert_awaited_once()
    asyncio.run(_run())


def test_llm_service_json_primary_and_fallback():
    """Test structured JSON generation priority (Custom Model -> Groq)."""
    async def _run():
        # 1. Primary succeeds
        with patch.object(custom_model_service, "is_available", return_value=True), \
             patch.object(custom_model_service, "generate_json", new_callable=AsyncMock) as mock_custom, \
             patch.object(llm_service, "_call_groq", new_callable=AsyncMock) as mock_groq:
            
            mock_custom.return_value = {"explanation": "Local model output", "key_points": ["Point A"]}
            res = await llm_service.generate_json(prompt="Explain momentum")
            assert res["explanation"] == "Local model output"
            mock_groq.assert_not_called()

        # 2. Primary fails -> Groq fallback succeeds
        with patch.object(custom_model_service, "is_available", return_value=True), \
             patch.object(custom_model_service, "generate_json", new_callable=AsyncMock) as mock_custom, \
             patch.object(llm_service, "_call_groq", new_callable=AsyncMock) as mock_groq:
            
            mock_custom.return_value = None
            mock_groq.return_value = '{"explanation": "Groq fallback output", "key_points": ["Point B"]}'
            res = await llm_service.generate_json(prompt="Explain momentum")
            assert res["explanation"] == "Groq fallback output"
    asyncio.run(_run())


def test_api_model_status_endpoint():
    """Test GET /api/v1/model/status endpoint."""
    response = client.get("/api/v1/model/status")
    assert response.status_code == 200
    data = response.json()
    assert "primary_model" in data
    assert "fallback_groq_configured" in data
    assert "status" in data


def test_api_model_test_query_forced_fallback():
    """Test POST /api/v1/model/test-query with force_fallback flag."""
    with patch.object(llm_service, "_call_groq", new_callable=AsyncMock) as mock_groq:
        mock_groq.return_value = "Groq forced test response."
        response = client.post(
            "/api/v1/model/test-query",
            json={
                "prompt": "Test physics prompt",
                "force_fallback": True
            }
        )
        assert response.status_code == 200
        data = response.json()
        assert data["provider"] == "Groq Cloud Fallback (Forced)"
        assert data["answer"] == "Groq forced test response."
